homeassistant:
  name: Home
  latitude:  !secret home_latitude
  longitude: !secret home_longitude
  elevation: 87
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "automation.*watchdog*":
      icon: mdi:timer
    "sensor.dark_sky_*":
      homebridge_hidden: true
    "scene.month_*_colors":
      hidden: true
      emulated_hue_hidden: true
      homebridge_hidden: true

  packages: !include_dir_named packages

http:
  base_url: !secret hass_url
  api_password: !secret web_interface_password
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_cert_key
  trusted_networks:
    - 192.168.42.0/24
    - !secret ipv6_network  # TODO: Add secret
  ip_ban_enabled: true
  login_attempts_threshold: 3

frontend:
  javascript_version: latest  # TODO: Check what this does

notify:
  - name: html5
    platform: html5

discovery:
  ignore:
    - samsung_tv
    - google_cast
    - plex_mediaserver

updater:
  include_used_components: true

sun:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

zabbix:
  host: !secret zabbix_host
  path: /
  ssl: True
  username: !secret zabbix_username
  password: !secret zabbix_password

logbook:
  exclude:
    entities:
      - automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
      - automation.cuckoo_clock
      - binary_sensor.office_motion
      - group.garage_doors
      - media_player.LivingRoomCC
      - py.warnings
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.small_garage_status
      - sensor.large_garage_status
      - sensor.small_garage_time_in_state
      - sensor.large_garage_time_in_state
      - sensor.large_garage_wifi_signal_strength
      - sensor.small_garage_wifi_signal_strength
      - sensor.small_garage_reflection_rate
      - sensor.large_garage_reflection_rate
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.time
      - sensor.date
      - sensor.floorplan_date
      - sensor.floorplan_time
      - sensor.ha_uptime

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.floorplan_date
      - sensor.floorplan_time
      - sensor.ha_uptime
      - sensor.time

logger: !include logger.yaml
recorder: !include recorder.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883
  username: hass
  password: !secret mqtt_password

media_player:
  - platform: sonos
  - platform: cast
  - platform: samsungtv
    host: 192.168.42.81
    mac: 50:85:69:0b:b9:6b
    name: DVR
  - platform: samsungtv
    host: 192.168.42.80
    mac: c4:73:1e:cb:75:8e
    name: TV

google:
  client_id:     !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

group:          !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor:         !include_dir_merge_list sensor
automation:     !include_dir_merge_list automations
scene:          !include_dir_merge_list scenes
script:         !include_dir_merge_named scripts
input_boolean:  !include_dir_merge_named input_boolean
input_select:   !include_dir_merge_named input_select
input_number:   !include_dir_merge_named input_number
shell_command:  !include_dir_merge_named shell_command
switch:         !include_dir_merge_list switch
zone:           !include_dir_merge_list zone
light:          !include_dir_merge_list light
climate:        !include_dir_merge_list climate
binary_sensor:  !include_dir_merge_list binary_sensor

conversation:
config:
wake_on_lan:
map:

asterisk_ami:
  host: localhost
  username: admin
  password: !secret asterisk_password
  monitor:
  - 100

tts:
  - platform: google
    language: 'en'
  - platform: amazon_polly
    aws_access_key_id: !secret aws_key
    aws_secret_access_key: !secret aws_secret
    region_name: 'eu-west-1'
    voice: Amy

tradfri:
  host:  192.168.42.51

feedreader:
  urls:
    - https://medium.com/feed/@sproggar

octoprint:
  host: 192.168.42.24
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

google_assistant:
  expose_by_default: true
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_api_key
