- platform: mqtt
  name: "Living Room Standing Lamp"
  state_topic: "stat/livingroom-standing-lamp/POWER"
  command_topic: "cmnd/livingroom-standing-lamp/POWER"
  qos: 1
  retain: true
- platform: mqtt
  name: "Living Room TV Lamp"
  state_topic: "stat/livingroom-tv-lamp/POWER"
  command_topic: "cmnd/livingroom-tv-lamp/POWER"
  qos: 1
  retain: true
- platform: mqtt
  name: "Christmas Tree"
  state_topic: "stat/sonoff-spare/POWER"
  command_topic: "cmnd/sonoff-spare/POWER"
  qos: 1
  retain: true
