- alias: "Turn off lights after a while"
  trigger:
    - platform: state
      entity_id:
        - light.bathroom
      to: 'on'
      for: '00:20:00'
  action:
    - service: light.turn_off:
      data_template:
        entity_id: {{trigger.entity_id}}
      transition: 60
