- alias: 'Christmas Tree On Morning'
  trigger:
    platform: time
    at: "07:00:00"
  action:
    service: light.turn_on
    entity_id: light.christmas_tree

- alias: 'Christmas Tree Off Morning'
  trigger:
    platform: time
    at: "09:00:00"
  action:
    service: light.turn_off
    entity_id: light.christmas_tree

- alias: 'Christmas Tree On Evening'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 4
  action:
    service: light.turn_on
    entity_id: light.christmas_tree

- alias: 'Christmas Tree Off Evening'
  trigger:
    platform: time
    at: "23:59:59"
  action:
    service: light.turn_off
    entity_id: light.christmas_tree

- alias: "Christmas Tree Off After Lights"
  trigger:
    platform: state
    entity_id: light.living_room_tv_lamp
    to: "off"
    for:
        minutes: 5
  action:
    service: light.turn_off
    entity_id: light.christmas_tree
