- alias: 'Dark house extra light'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation}}'
      below: 20.0
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage  #TODO: Add dark sky sensors
      above: 90
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1
    - platform: state
      entity_id: group.family  #TODO: Create group
      to: 'home'
      from: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: and
            conditions:
            - condition: numeric_state
              entity_id: sun.sun
              value_template: '{{ state.attributes.elevation }}'
              below: 20
            - condition: numeric_state
              entity_id: sensor.dark_sky_cloud_coverage
              above: 90
          - condition:
            numeric_state: sensor.dark_sky_precip_intensity
            above: 1
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: state
        entity_id: group.family
        state: 'home'
  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_standing_lamp
        - light.living_room_tv_lamp
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.daylight_override  #TODO: Create
    - service: script.speech_engine  #TODO: Create
      data_template:
        value1: "It is getting a little dark inside the house because of the {{trigger.entity_id.split('_')[2]|replace('precip','rain') }} {{trigger.entity_id.split('_')[3]|replace('intensity',' ')}} outside.  I will turn on some extra lights in the living room."
