- alias: 'Evening Lights'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 4
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_evening
      data:
        transition: 600
    - service: scene.turn_on
      entity_id: scene.living_room_evening
      data:
        transition: 600
