- alias: House Mode morning
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Morning
  action:
    service: scene.turn_on
    entity_id: scene.house_mode_morning

- alias: House Mode Day
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Day
  action:
    service: scene.turn_on
    entity_id: scene.house_mode_day

- alias: House Mode Evening
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Evening
  action:
    service: scene.turn_on
    entity_id: scene.house_mode_evening

- alias: House Mode Night
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Night
  action:
    service: scene.turn_on
    entity_id: scene.house_mode_night
