- alias: "Morning Greeting"
  trigger:
    - platform: time
      at: '08:30:00'
  condition:
    - condition: state
      entity_id: device_tracker.phone_jacobphone
      state: 'home'
  action:
    - service: script.jarvis_greeting

