- alias: "Bathroom lights on - Morning"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
  condition:
    - condition: time
      before: '07:00:00'
  action:
    - service: light.turn_on
      entity_id: light.bathroom_light
      data:
        profile: relax
        transition: 1

