- alias: "Turn things off at sunrise"
  trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'
  action:
    - service: script.interior_off #TODO: Create script
    - delay: '00:{{ (range(1, 55)|random|int) }}:00'
    - service: light.turn_off
      entity_id:
        - light.all_lights #TODO: Create group
    - wait_template: "{{ states.sun.sun.state == 'above_horizon' }}"
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.guest_mode
