- platform: darksky
  api_key:  !secret darksky_api_key
  monitored_conditions:
    - daily_summary
    - hourly_summary
    - apparent_temperature
    - cloud_cover
    - humidity
    - icon
    - minutely_summary
    - nearest_storm_distance
    - precip_intensity
    - precip_intensity_max
    - summary
    - temperature
    - uv_index
    - wind_speed
    - precip_probability
    - pressure
    - pressure
    - wind_bearing
- platform: moon
- platform: opensky
  radius: 10
